---
apiVersion: v1
kind: Service
metadata:
  name: example-service-metrics
  namespace: vessel-platform
  labels:
    app: example-service
spec:
  type: ClusterIP
  selector:
    app: example-service
    instance: app
  ports:
    - port: 9102
      targetPort: 9102
